POST http://localhost:4000/pictures/
Content-Type: application/json

{
    "name": "Gustavo"
}

### 
GET http://localhost:4000/pictures/


### 
GET http://localhost:4000/pictures/65359b064b7abdda0b308b22


### 
DELETE http://localhost:4000/pictures/65359a2743



